### ISSUE TITLE
Console error: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by TutoCriss64** [TheLeerName/mania-converter#5]
Why I always got this error? I run this cmd: `ManiaConverter.exe "-fileinput:beatmap" "-fileoutput:converted" "-mode:2" "-side:1" "-key:4" "-artist:Artist"`

```
C:\Local\mania\lib\Utils.js:106
                map[i] = map_[i].toString();
                                ^

TypeError: Cannot read property 'toString' of undefined
    at Object.exports.getMapOptions (C:\Local\mania\lib\Utils.js:106:19)
    at fnf_to_osu (C:\Local\mania\lib\Converter.js:420:22)
    at Object.exports.convert (C:\Local\mania\lib\Converter.js:14:13)
    at Object.<anonymous> (C:\Local\mania\index.js:33:23)
```

**Comment by TheLeerName** [comment]
uh, you sure what you have `beatmap.json` in folder with converter?

**Comment by TheLeerName** [comment]
check new update, maybe it fixed

**Comment by TutoCriss64** [comment]
> check new update, maybe it fixed

it fixed, thanks!
